export const GET_WALLET_LOADING= 'GET_WALLET_LOADING';
export const GET_WALLET_SUCCESS = 'GET_WALLET_SUCCESS';
export const GET_WALLET_FAIL = 'GET_WALLET_FAIL';
export const INIT_GET_WALLET = 'INIT_GET_WALLET';

export const CREATE_WALLET_LOADING= 'CREATE_WALLET_LOADING';
export const CREATE_WALLET_SUCCESS = 'CREATE_WALLET_SUCCESS';
export const CREATE_WALLET_FAIL = 'CREATE_WALLET_FAIL';
export const INIT_CREATE_WALLET = 'INIT_CREATE_WALLET';

export const STAKE_OVERVIEW_LOADING= 'STAKE_OVERVIEW_LOADING';
export const STAKE_OVERVIEW_SUCCESS = 'STAKE_OVERVIEW_SUCCESS';
export const STAKE_OVERVIEW_FAIL = 'STAKE_OVERVIEW_FAIL';
export const INIT_STAKE_OVERVIEW= 'INIT_STAKE_OVERVIEW';

export const APPROVE_STAKE_LOADING= 'APPROVE_STAKE_LOADING';
export const APPROVE_STAKE_SUCCESS = 'APPROVE_STAKE_SUCCESS';
export const APPROVE_STAKE_FAIL = 'APPROVE_STAKE_FAIL';
export const INIT_APPROVE_STAKE = 'INIT_APPROVE_STAKE';


export const APPROVE_CLAIM_LOADING= 'APPROVE_CLAIM_LOADING';
export const APPROVE_CLAIM_SUCCESS = 'APPROVE_CLAIM_SUCCESS';
export const APPROVE_CLAIM_FAIL = 'APPROVE_CLAIM_FAIL';
export const INIT_APPROVE_CLAIM = 'INIT_APPROVE_CLAIM';

export const CHECK_APPROVE_CLAIM_STATUS_LOADING= 'CHECK_APPROVE_CLAIM_STATUS_LOADING';
export const CHECK_APPROVE_CLAIM_STATUS_SUCCESS = 'CHECK_APPROVE_CLAIM_STATUS_SUCCESS';
export const CHECK_APPROVE_CLAIM_STATUS_FAIL = 'CHECK_APPROVE_CLAIM_STATUS_FAIL';
export const INIT_CHECK_APPROVE_CLAIM_STATUS = 'INIT_CHECK_APPROVE_CLAIM_STATUS';


export const STAKE_STATUS_LOADING= 'STAKE_STATUS_LOADING';
export const STAKE_STATUS_SUCCESS = 'STAKE_STATUS_SUCCESS';
export const STAKE_STATUS_FAIL = 'STAKE_STATUS_FAIL';
export const INIT_STAKE_STATUS= 'INIT_STAKE_STATUS';

export const CHECK_APPROVE_STAKE_STATUS_LOADING= 'CHECK_APPROVE_STAKE_STATUS_LOADING';
export const CHECK_APPROVE_STAKE_STATUS_SUCCESS = 'CHECK_APPROVE_STAKE_STATUS_SUCCESS';
export const CHECK_APPROVE_STAKE_STATUS_FAIL = 'CHECK_APPROVE_STAKE_STATUS_FAIL';
export const INIT_CHECK_APPROVE_STAKE_STATUS = 'INIT_CHECK_APPROVE_STAKE_STATUS';

export const STAKE_LOADING= 'STAKE_LOADING';
export const STAKE_SUCCESS = 'STAKE_SUCCESS';
export const STAKE_FAIL = 'STAKE__FAIL';
export const INIT_STAKE= 'INIT_STAKE';

export const STAKE_LISTS_LOADING= 'STAKE_DATA_LOADING';
export const STAKE_LISTS_SUCCESS = 'STAKE_DATA_SUCCESS';
export const STAKE_LISTS_FAIL = 'STAKE_DATA_FAIL';
export const INIT_STAKE_LISTS= 'INIT_STAKE_DATA';


export const CLAIM_LOADING= 'CLAIM_LOADING';
export const CLAIM_SUCCESS = 'CLAIM_SUCCESS';
export const CLAIM_FAIL = 'CLAIM_FAIL';
export const INIT_CLAIM= 'INIT_CLAIM';

export const CLAIM_STATUS_LOADING= 'CLAIM_STATUS_LOADING';
export const CLAIM_STATUS_SUCCESS = 'CLAIM_STATUS_SUCCESS';
export const CLAIM_STATUS_FAIL = 'CLAIM_STATUS_FAIL';
export const INIT_CLAIM_STATUS= 'INIT_CLAIM_STATUS';


export const UNSTACK_LOADING= 'UNSTACK_LOADING';
export const UNSTACK_SUCCESS = 'UNSTACK_SUCCESS';
export const UNSTACK_FAIL = 'UNSTACK_FAIL';
export const INIT_UNSTACK= 'INIT_UNSTACK';

export const UNSTACK_STATUS_LOADING= 'UNSTACK_STATUS_LOADING';
export const UNSTACK_STATUS_SUCCESS = 'UNSTACK_STATUS_SUCCESS';
export const UNSTACK_STATUS_FAIL = 'UNSTACK_STATUS_FAIL';
export const INIT_UNSTACK_STATUS= 'INIT_UNSTACK_STATUS';

export const SEND_LOADING= 'SEND_LOADING';
export const SEND_SUCCESS = 'SEND_SUCCESS';
export const SEND_FAIL = 'SEND_FAIL';
export const INIT_SEND= 'INIT_SEND';

export const SEND_STATUS_LOADING= 'SEND_STATUS_LOADING';
export const SEND_STATUS_SUCCESS = 'SEND_STATUS_SUCCESS';
export const SEND_STATUS_FAIL = 'SEND_STATUS_FAIL';
export const INIT_SEND_STATUS= 'INIT_SEND_STATUS';